### ISSUE TITLE
Is there any way to change the camera?

### ISSUE THREAD

**Issue by jldelda** [irawinder/Colortizer#2]
I am trying to set Colortizer with a MacBook Pro and a Logitech c270 camera. However, when I start Colortizer it uses by default the camera of the laptop (located in the screen). I need Colortizer to use the added camera I am connecting through usb.

Is there any way to change the default camera used by Colortizer? Has any experienced the same problem with Mac?

**Comment by jldelda** [comment]
Solved! I run Facetime in Mac, changed the camera to the USB one, closed Facetime and open Colortizer.

It seems Mac does not have webcam settings, but it does in each application, and somehow the settings of applications are connected.

**Comment by irawinder** [comment]
You may also change the camera index directly in the code: 

_// Position within array that describes available cameras_
`int camera = 0;`

Processing indexes all available cameras when you run your application.  The index value for all available cameras is printed to the Processing console when you run Colortizer. For instance, the index of the camera you may be trying to use might be something other than zero.
